### ISSUE TITLE
go-oci8

### ISSUE THREAD

**Issue by MichaelS11** [cjbj/test#1]
@cjbj Do you post in goracle things like:

> Does the same thing happen in https://github.com/mattn/go-oci8/?

Because I think it would be nice if you stopped posting things like that in go-oci8.

cc @mattn

**Comment by cjbj** [comment]
@MichaelS11 apologies, I am just curious to know if this is a Go limitiation.  I respect your efforts with go-oci8.

**Comment by MichaelS11** [comment]
Thanks. Maybe give other troubleshooting options a change to work first. Can leave using another repo as a last resort if we can not fix the issue in a reasonable amount of time.

**Comment by cjbj** [comment]
I'm always awed by how much personal investment open source developers put into their projects, and how little appreciated it is, particularly when answering user questions.

Contact me anytime you have OCI or DB issues.

If you send me your email address, I'd be happy to keep you in the loop on things like https://blogs.oracle.com/opal/oracle-instant-client-downloadable-without-login-breaking-news and also to be able to understand what features & direction you think Oracle needs.

**Comment by cjbj** [comment]
PS my email address is in my profile.

**Comment by MichaelS11** [comment]
Thank you kindly. Much appreciated :)
